### ISSUE TITLE
hello! There is a bug in the program 

### ISSUE THREAD

**Issue by xiaolinjieer** [guojia-git/watermarking-cnn-classifiers#1]
FileNotFoundError: [Errno 2] No such file or directory: './2017-10-02_vgg16.t7'?

**Comment by guojia-git** [comment]
I haven't touched the project for a long time. I think you'll need to train the model yourself  https://github.com/kuangliu/pytorch-cifar.

**Comment by xiaolinjieer** [comment]
could you tell me why to do  this?

**Comment by xiaolinjieer** [comment]
could you tell me why to do  this?

> I haven't touched the project for a long time. I think you'll need to train the model yourself https://github.com/kuangliu/pytorch-cifar.
